### ISSUE TITLE
请问最终的最高精度能达到多少？

### ISSUE THREAD

**Issue by dinghuanghao** [ShunLu91/Single-Path-One-Shot-NAS#10]
README中只写从Supernet随机采样的1000个子网络的精度，请问结构搜索之后的最优子结构finetune or train from scratch的最高的精度能否超过原始ShuffleNet的精度？

**Comment by ShunLu91** [comment]
这确实是一个好问题，但由于资源不太充足以及re-train超参设置的公平性问题个人没有经验，所以re-train这一步我就没有继续进行（因为在cifar-10数据集很少看到有基于mobilenet/shufflenet block的网络进行re-train，SPOS原文也没有这样的实验结果，所以没有可参考的基准）
但是你问的这个问题可以从ImageNet数据集去评估，官方的代码以及论文中，给出了使用SPOS在ImageNet数据集搜索得到最优子结构train from scratch的最高精度是可以超过原始ShuffleNet精度的
