### ISSUE TITLE
Randomly sample and save models

### ISSUE THREAD

**Issue by abhishektyaagi** [ShunLu91/Single-Path-One-Shot-NAS#13]
Hi,
Thank you for this work. I am hoping to use it to carry out some experiments.

I was hoping to use the pre-trained CIFAR-10 supernet to sample some 1k architectures (randomly) and save their checkpoints/weights. My objective is to save these random models, modify the weights and then do the validation. 

Is it possible for you to elaborate on how I can save the randomly sampled weights?

**Comment by ShunLu91** [comment]
Hi,
I think first you can load the weights into the supernet, and then inherit the weights from the supernet for each sampled architecture. Specifically, your can obtain the weights from the supernet for each selected operation per layer according to the predifined operation name. 
Hope my answer will help you.

**Comment by abhishektyaagi** [comment]
Thank you for your quick response.

I am actually a bit confused as to how I can implement the approach you mentioned above. Let me try to break it down as per my understanding:
1. First I will load the pre-trained weights of the supernet.
2. Once the weights for the supernet are loaded, I can generate a list (choice) that will select the random architecture

Now my questions are:

1. How do I do this: "Specifically, you can obtain the weights from the supernet for each selected operation per layer according to the predefined operation name."
2. Is it possible for me to save the random-selected model just like we can save any other model in PyTorch?

I appreciate your help!

**Comment by ShunLu91** [comment]
As for your two questions:

1. The supernet weights is a dict. Each selected operation per layer can be seen as a 'key' for this dict, so you can obtain its corresponding weights from this dict as long as you have the right operation name i.e. the 'key'. The operation name is usually pre-defined when you initialize the model.
2. It's not that convenient. You should first initialize a random-selected model, and then inherit weights for each operation in the random-selected model as above, and finally you can save this model with its weights as any other model in PyTorch.

If you have any questions, please feel free to ask.

**Comment by ShunLu91** [comment]
As there are no update recently, I will close this issue.
Feel free to re-open it if you have any question.
