### ISSUE TITLE
BN校准

### ISSUE THREAD

**Issue by zhanglei1172** [ShunLu91/Single-Path-One-Shot-NAS#15]
请问为什么不在搜索评估子网的时候不进行BN校准？在https://github.com/megvii-model/SinglePathOneShot/blob/master/src/Search/tester.py#L52 代码中有对BN进行校准，请问不进行BN校准这样会不会带来较大的偏差？

**Comment by ShunLu91** [comment]
抱歉，确实当初在实现的时候忽略了这一点。
个人推测，既然SPOS论文专门提到了需要做BN校准，那么BN校准应该是可以带来正向收益的。但是，我在实践中通常没有进行BN校准这一步，得到的子网精度也还可以接受。另外，我在NAS-Bench-201上进行实验时，使用SPOS算法且没有BN校准也可以得到合理的子模型排序。
综上，我估计使用BN校准要比不使用要好，但二者之间的差距可能并不是那么大，具体差异的大小还是需要实验来说明。

**Comment by haiduo** [comment]
恰恰我发现，BN校准评估或者说校准的图片太多后的精度有点离谱，相反直接BN继承评估的结果貌似更合理些
