### ISSUE TITLE
关于Mixed-Precision Quantization

### ISSUE THREAD

**Issue by qianhuiliu** [ShunLu91/Single-Path-One-Shot-NAS#16]
请问有关于Mixed-Precision Quantization这个application的实现吗？谢谢

**Comment by ShunLu91** [comment]
您好，我自己没有这方面的相关实现，但我帮您找到了几个可参考的Repo：

（1）SPOS论文中在混合精度量化章节引用的相关工作：
- https://github.com/KwangHoonAn/PACT
- https://github.com/zzzxxxttt/pytorch_DoReFaNet

（2）关于混合精度量化位宽搜索的相关工作：
- 可微分搜索：https://github.com/zhaoweicai/EdMIPS
- 强化学习搜索：https://github.com/mit-han-lab/haq

最后，也推荐一下我们自己的轻量化工具[StarLight](https://github.com/ICT-ANS/StarLight)，其中提供了模型指定位宽量化和集成演示的示例，欢迎试用~
