### ISSUE TITLE
请问下，在block selection时，不同的branch之间会共享权重么？

### ISSUE THREAD

**Issue by junleiz** [ShunLu91/Single-Path-One-Shot-NAS#3]
您好，非常感谢您的贡献，在阅读您的代码的时候，不同branch之间是不共享权重的，但是在论文中说了一个共享权重的问题，即预先创建一个很大的权重，然后分割给不同的branch。请问下这个共享权重是仅仅在channel selection时候才有还是您没有实现呢

**Comment by ShunLu91** [comment]
1、在block selection时，不同branch的参数量是不一致的。个人认为文中的共享的意思是同一个block的参数共享到下一次迭代中。
2、channel selection目前没有实现。
