### ISSUE TITLE
net output dimension mismatch on cifar10

### ISSUE THREAD

**Issue by lucaskyle** [ShunLu91/Single-Path-One-Shot-NAS#5]
hey there:

when i run python train_CIFAR-10.py

Batch_size=128
so the output of network  should be (128,10)
i got (512,10)

ValueError: Expected input batch_size (512) to match target batch_size (128).

**Comment by lucaskyle** [comment]
should i  modify the Network?

**Comment by lucaskyle** [comment]
ok i checked official magvii code    
seems like u r working on training supernet on cifar10？

**Comment by lucaskyle** [comment]
the  gap_size   should be 2

**Comment by ShunLu91** [comment]
Thanks! I will fix these bugs.

**Comment by lucaskyle** [comment]
this is so strange 
the train loss is still  Loss: 2.303  
it didnt converge

i try other models that the train loss reduced easily...

maybe sth wrong in the supernetwork.
i will check magvii codes and their supermodel.

**Comment by ShunLu91** [comment]
Sorry, there are some bugs in the model.py and it has been fixed now. You can refer to the latest version of the code.

**Comment by lucaskyle** [comment]
its the learning rate  
seems like u fixed it.

thx
