### ISSUE TITLE
about extracting final result

### ISSUE THREAD

**Issue by lucaskyle** [ShunLu91/Single-Path-One-Shot-NAS#6]
thx for updating dude:
 I run the train_cifar10 code
 there is nothing but model_save function after train_search.
 I guess the final result after train_search should be like [3 3 1 3 0 1 0 2 2 2 0 3 1 1 0 1 2 1 1 1] 
,right?
 

we may load that configuration and Get Searched Architecture like: 
config = [3 3 1 3 0 1 0 2 2 2 0 3 1 1 0 1 2 1 1 1] 
outputs = model(inputs, config)
am i right?

then we can train it on cifar10 to see how good is
maybe I can do this.

one more question:
I found 
   random = np.random.randint(4, size=20)
   outputs = model(inputs, random)
both in train and validate  function,
do u mean these two random configrations should be same or not?

**Comment by lucaskyle** [comment]
[Val_Accuracy] epoch:210, top1:50.11000%, top5:93.61000% 

maybe 600 epochs by default are not enough...

**Comment by ShunLu91** [comment]
The main problem is that CIFAR-10 only has 32x32 inputs which will downsample to 1x1 after 5 downsamples in this supernet. There are two solutions for this: one is that shrink this supernet and 2 downsample layers are enough，another is that resize CIFAR-10 images to (224,224,3) just like transfer learning in EfficientNet and so on. The accuracy will increase a lot.
