### ISSUE TITLE
您好，关于精度复现

### ISSUE THREAD

**Issue by hrtan** [ShunLu91/Single-Path-One-Shot-NAS#7]
打扰一下：

    在运行600个Epoch后，并没有在val set上面达到你绘制的 精度分布图。请问你提供的这个分布图是 train set上面的吗？

**Comment by ShunLu91** [comment]
这个是使用supernet.py在CIFAR-10上训练了600个epoch ，然后使用random_search.py随机搜索了1000个模型绘制的，精度是在val set进行测试的，并不是train set

**Comment by CuriousCat-7** [comment]
> 打扰一下：
> 
> ```
> 在运行600个Epoch后，并没有在val set上面达到你绘制的 精度分布图。请问你提供的这个分布图是 train set上面的吗？
> ```

我也是，我的结果在87 - 88之间，没有如图所示的在91-92之间

**Comment by ShunLu91** [comment]
如果结果集中在87-88之间，感觉基本上复现差距不大。
另外你可以试试我提供的checkpoint，那个是我当时训练保存下来的超网权重。时间确实比较久了，所以我印象也不是太深，等最近有空了，我再固定种子重新验证一下，更新这个结果
