### ISSUE TITLE
Can not find cifar_train.py

### ISSUE THREAD

**Issue by ArronYao** [ShunLu91/Single-Path-One-Shot-NAS#8]
In your usage, you wrote that: 
python cifar_train.py exp_name spso_cifar

But  I can not find cifar_train.py in your repository.

**Comment by ShunLu91** [comment]
I changed the name of the code and forgot to change the README.
Thanks for reminder and it has been fixed.

**Comment by ArronYao** [comment]
I see. Thanks for your help.
